# Generated by Django 2.1.2 on 2018-10-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=40)),
                ('Product_Catagory', models.CharField(max_length=40)),
                ('Capacity', models.CharField(max_length=40)),
            ],
        ),
    ]
