# Generated by Django 2.1.2 on 2018-11-03 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181103_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(max_length=3)),
                ('camera', models.IntegerField(max_length=3)),
                ('ram', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='Capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductDetails'),
        ),
    ]
