# Generated by Django 2.1.2 on 2018-11-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181103_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneModel', models.CharField(max_length=40)),
                ('os', models.CharField(choices=[('A', 'Android'), ('I', 'IOS'), ('M', 'Microsoft')], max_length=1)),
                ('internal_memory', models.CharField(choices=[('1', '1 GB'), ('2', '2 GB'), ('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB')], max_length=3)),
                ('RAM', models.CharField(choices=[('1', '1 GB'), ('2', '2 GB'), ('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB')], max_length=3)),
                ('color', models.CharField(choices=[('Gold', (('Rose', 'Rose Gold'),)), ('Silver', (('Gold', 'Silver Gold'),)), ('White', (('Gold', 'White Gold'),)), ('Blue', (('Royal', 'Royal Blue'),)), ('Black', (('Gray', 'Gray'), ('Midnight', 'Midnight Bkack'))), ('Roral', (('Lavender', 'Roral Lavender'), ('Stone', 'Roral Stone'), ('Yellow', 'Roral Yellow'), ('Apricot', 'Roral Apricot'), ('Pink', 'Roral Pink'), ('Orange', 'Roral Orange')))], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='brands',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Capacity',
        ),
        migrations.AlterField(
            model_name='brands',
            name='catagory',
            field=models.CharField(choices=[('Phone', 'Mobile'), ('Laptop', 'Computer'), ('Camera', 'DSLR'), ('Pad', 'Tablet'), ('Smart Watch', 'Watch'), ('Electronis', 'Home Appliance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Phones'),
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.AddField(
            model_name='phones',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Brands'),
        ),
    ]
