# Generated by Django 2.1.3 on 2018-12-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PhoneModel', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('os', models.CharField(choices=[('A', 'Android'), ('I', 'IOS'), ('M', 'Microsoft')], max_length=1)),
                ('internal_memory', models.CharField(choices=[('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB')], max_length=3)),
                ('RAM', models.CharField(choices=[('1', '1 GB'), ('2', '2 GB'), ('3', '3 GB'), ('4', '4 GB'), ('8', '8 GB')], max_length=3)),
                ('color', models.CharField(choices=[('Gold', (('Rose', 'Rose Gold'),)), ('Silver', (('Gold', 'Silver Gold'),)), ('White', (('Gold', 'White Gold'),)), ('Blue', (('Royal', 'Royal Blue'),)), ('Black', (('Gray', 'Gray'), ('Midnight', 'Midnight Bkack'))), ('Roral', (('Lavender', 'Roral Lavender'), ('Stone', 'Roral Stone'), ('Yellow', 'Roral Yellow'), ('Apricot', 'Roral Apricot'), ('Pink', 'Roral Pink'), ('Orange', 'Roral Orange')))], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Brand')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Catagory')),
            ],
        ),
    ]
