# Generated by Django 2.1.2 on 2018-11-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=40)),
                ('catagory', models.CharField(max_length=40)),
                ('items_list', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
                ('Capacity', models.CharField(max_length=40)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Brands')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
