# Generated by Django 2.1.3 on 2018-12-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='Brand',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='id',
        ),
        migrations.AlterField(
            model_name='brand',
            name='manufacturer',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='catagory',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
