# Generated by Django 2.1.2 on 2018-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181111_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='catagory',
            field=models.CharField(choices=[('Mobile', 'Phone'), ('Laptop', 'Computer'), ('Camera', 'DSLR'), ('Pad', 'Tablet'), ('Smart Watch', 'Watch'), ('Electronis', 'Home Appliance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='phones',
            name='RAM',
            field=models.CharField(choices=[('1', '1 GB'), ('2', '2 GB'), ('3', '3 GB'), ('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB')], max_length=3),
        ),
        migrations.AlterField(
            model_name='phones',
            name='internal_memory',
            field=models.CharField(choices=[('1', '1 GB'), ('2', '2 GB'), ('3', '3 GB'), ('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB')], max_length=3),
        ),
    ]
