# Generated by Django 2.1.2 on 2018-11-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181111_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='model_name',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
